services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./TP2/1-ScriptCreacion_DB/CreacionSTG_Universidad.sql:/docker-entrypoint-initdb.d/01-CreacionSTG_Universidad.sql:ro
      - ./TP2/1-ScriptCreacion_DB/CreacionDWH_Universidad.sql:/docker-entrypoint-initdb.d/02-CreacionDWH_Universidad.sql:ro

  metabase:
    image: metabase/metabase:v0.61.2.10
    container_name: metabase
    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - mysql

    volumes:
      - metabase_data:/metabase.db

volumes:
  mysql_data:
  metabase_data:
