services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./TP2/1-ScriptCreacion_DB/CreacionSTG_Universidad.sql:/docker-entrypoint-initdb.d/01-CreacionSTG_Universidad.sql:ro
      - ./TP2/1-ScriptCreacion_DB/CreacionDWH_Universidad.sql:/docker-entrypoint-initdb.d/02-CreacionDWH_Universidad.sql:ro

volumes:
  mysql_data: