FROM python:3.11-slim

# Instalar dependencias de sistema necesarias para el cliente de MySQL
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    gcc \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Upgrade pip
RUN pip install --upgrade pip

# Instalar librerías de tu proyecto
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el código del TP al contenedor
COPY . .

# Comando por defecto (lo sobreescribiremos en el docker-compose)
CMD ["python"]
